apiVersion: app.k8s.io/v1beta1com
kind: Application
metadata:
  name: sno2-john-com
  namespace: ztp-clusters
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - sno2-john-com
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: clusters/sno2-john-com
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: sno2-john-com
  name: cluster-sno2-tor-subscription-1
  namespace: ztp-clusters
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: local-cluster
