apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config-map
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
  
    -----END CERTIFICATE-----
    
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-release"
    #mirror-by-digest-only = false

    [[registry.mirror]]
    location = "quay.john.com:8443/ocp4/openshift4"
    insecure = false

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
    #mirror-by-digest-only = false

    [[registry.mirror]]
    location = "quay.john.com:8443/ocp4/openshift4"
    insecure = false

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhacm2"
    #mirror-by-digest-only = false

    [[registry.mirror]]
    location = "quay.john.com:8443/rhacm2"
    insecure = false

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/multicluster-engine"
    #mirror-by-digest-only = false

    [[registry.mirror]]
    location = "quay.john.com:8443/multicluster-engine"
    insecure = false
