apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster1-john-com
  namespace: cluster1-john-com
spec:
  baseDomain: john.com
  clusterName: ztpcluster1
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: cluster1-john-com
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "cluster1"
  pullSecretRef:
    name: pull-secret
